Fix: Remove setFlipX() call on Rectangle objects
Rectangle objects in Phaser don't support setFlipX() method, only Sprite
objects do. Since we're using rectangles as placeholders, removed the call
to prevent TypeError during updateSprite().

This will be re-enabled when we switch to actual sprite assets.

Fixes: Uncaught TypeError: this.sprite.setFlipX is not a function